version: '3'

services:
  app:
    build:
      context: "./"              
    volumes:
      - "./:/usr/src/"
      - "waifu-cache:/root/.cache"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
volumes:
  waifu-cache: